### ISSUE TITLE
"DETECTION" Support Missing for mfkeys32 Attack

### ISSUE THREAD

**Issue by digitalentropy** [RfidResearchGroup/ChameleonMini#13]
On Latest RRG firmware (2020-02-03) DETECTION command appears to be missing from "HELP", breaking mfkeys32 functionality in the Windows GUI.

Log output from GUI:

```
[=] Connecting to USB Serial Device (COM13) at COM13
[!] Firmware doesn't support DETECTION cmd -- mfkey32 key recovery is not possible
[+] Success, found Chameleon Mini device on 'COM13' with Firmware RevG Official installed
```

**Comment by iceman1001** [comment]
The bug is most likely here.
https://github.com/RfidResearchGroup/ChameleonMini/blob/proxgrind/Firmware/Chameleon-Mini/Terminal/CommandLine.c#L334

The three extra commands is added after the supposed "last item" object.

**Comment by tssmcu** [comment]
Actually, Willok upgrade the DETECTION function, The new mfkey32 is powerful than before.
The new mfkey32 V2 can continuously record hundreds of traces, So we changed the way of communication and the data structure. New DETECTION(mfkey32v2) need to use Xmodem to download LOG file. then calculate mfkey32v2 with the log data.
Here is the DETECTION log data format in the attach.
[Uploading REV.G_Detection(Mfkey32V2) Log format explain.pdf…]()

**Comment by tssmcu** [comment]
Hope the  GUI can support new mfkey32 soon :)

**Comment by iceman1001** [comment]
That link doesn't work. 

In order for cross application interaction to work, we need documentation over what has been done,  how to use.  When you make breaking changes like that,  don't expect anything to work with other applications. 

GUI most likely will not be updated for some time.

**Comment by tssmcu** [comment]
I know, Try again, the  link  should work now.

**Comment by iceman1001** [comment]
Link works.  Doesn't solve this issue. 
So this issue needs to be addressed.

**Comment by db69** [comment]
Can we have MFkey32V2 without calling home through XMODEM;  we do not want our keys to be collected by 3rd parties !  Had the same issue with RFIDTools.  
Logfile can be loaded in memory, and we will need to use the Chameleon in places without network access

**Comment by tssmcu** [comment]
I think you misunderstood our APP，The both of the APP does not need network at all.
They all run completely offline.
XMODEM is a UART based communication protocol. It's nothing to do with network.
the XMODEM protocol used  to transmit large amounts of data，like dump file.
Hope you enjoy :)

**Comment by db69** [comment]
Thanks for the clarification.
My mistake !
Btw, I cannot het Bluetooth working (same as issue #8) any suggestion ?
Thanks anyway.
Kind Regards.



Sent from Samsung tablet.



-------- Original message --------

**Comment by Ziglar1** [comment]
the 2020-07-14 firmware supports the original question. 
[2020-07-14_Chameleon.zip](https://github.com/RfidResearchGroup/ChameleonMini/files/5162079/2020-07-14_Chameleon.zip)
